version: "2.1"

services:
  web:
    image: docksal/web:2.3-apache2.4
    volumes:
      - ${PROJECT_ROOT}:/var/www
    environment:
      - APACHE_DOCUMENTROOT=/var/www/public
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
      - io.docksal.project-name=${PROJECT_NAME}
    depends_on:
      - db

  cli:
    image: docksal/cli:2.12-php7.4
    volumes:
      - ${PROJECT_ROOT}:/var/www
    environment:
      - VIRTUAL_HOST=laravel.docksal
      - DOCROOT=public
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=default
    depends_on:
      - db

  db:
    image: docksal/db:1.4-mysql-5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=default
    volumes:
      - docksal-db-data:/var/lib/mysql

volumes:
  docksal-db-data:
